version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" # La ubicación de tu archivo pom.xml o build.gradle
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 5 # Máximo de PRs abiertos al mismo tiempo  
