version: 2
updates:
  # Revisa las dependencias del ecosistema de Maven (o Gradle)
  - package-ecosystem: "gradle" # o "gradle" si estás usando Gradle
    directory: "/" # La ubicación de tu archivo pom.xml o build.gradle
    schedule:
      interval: "daily" # Puedes cambiar a "daily" o "monthly" según tus necesidades
    open-pull-requests-limit: 10 # Máximo de PRs abiertos al mismo tiempo
registries:
  github:
    type: "maven"
    url: "https://maven.pkg.github.com/willclever/test-gradle-biblioteca"
    username: "WillClever"
    password: "${{ secrets.DEPENDABOT_PACKAGE_REGISTRY_TOKEN }}"    
